fix subscribe all

diff --git a/honk-manage b/honk-manage
--- a/honk-manage
+++ b/honk-manage
@@ -7,26 +7,31 @@ usage(){
     cat >&2
     exit 1
 }<<\EOF
-honk-manage _port_ up|down|random|(sleep _time_)
+honk-manage _port_ up|down|random|(sleep _time_)|(subscribe-all totalServers)
 random sleeps for RANDOM % (60*60) time
 EOF
 
 init(){
     mkdir -p "$datadir" || exit 1
-    cd "$datadir" || exit 1
 
     uname="$machine$port"
     pw="$uname"
     listen="127.0.0.1:$port"
     domain="$port.$machine.ashwink.com.np"
 
-    printf "%s\n" "$uname" "$pw" "$listen" "$domain" |
-	honk init || exit 1
+    (
+	cd "$datadir" || die "couldn't cd to $datadir"
+	printf "%s\n" "$uname" "$pw" "$listen" "$domain" |
+	    honk init || exit 1
+    )
     up
 }
 
 up(){
-    honk --viewdir="$viewdir" &
+    (
+	cd "$datadir" || die "couldn't cd to $datadir"
+	honk --viewdir="$viewdir" &
+    )
 }
 
 down() {
@@ -50,7 +55,13 @@ random_sleep(){
 }
 
 subscribe_all(){
-    die "not implemented"
+    total=$1
+    for m in "${allmachines[@]}"; do
+	for ((i=0; i<"$total"; i++)); do
+	    pp=$((5000+i))
+	    honk-subscribe "$port.$machine.ashwink.com.np" "$machine$port" "https://$pp.$m.ashwink.com.np/u/$m$pp"
+	done
+    done
 }
 
 set -x
@@ -89,7 +100,8 @@ elif [[ $task = "init" ]]; then
     exit
 fi
 
-cd "$datadir" || exit 1
+[[ -d "$datadir" ]] || die "couldn't find $datadir"
+
 honkPid="$(lsof -i "@0.0.0.0:$port" | awk 'NR==2 {print $2}')"
 
 case $task in
@@ -115,7 +127,8 @@ case $task in
 	rm -r "$datadir"
 	;;
     subscribe-all)
-	subscribe-all
+	[[ $1 ]] || usage "subscribe-all _totalServers_"
+	subscribe_all "$@"
 	exit 1
 	;;
     *)
diff --git a/honk-manager b/honk-manager
--- a/honk-manager
+++ b/honk-manager
@@ -24,7 +24,7 @@ get_servers(){
     #$1 folders upped and stored in servers array
     for (( i=0; i<"$totalservers"; i++)); do
 	port=$((5000+i))
-	honk-manage "$port" up || exit 1
+	honk-manage "$port" init || exit 1
 	up_servers=("${up_servers[@]}" "$port")
     done
     wait
@@ -61,7 +61,7 @@ up_servers_func(){
 subscribe_all(){
     for (( i=0; i<"$totalservers"; i++)); do
 	port=$((5000+i))
-	honk-manage "$port" subscribe-all || die "couldn't subscribe by $port"
+	honk-manage "$port" subscribe-all "$totalservers" || die "couldn't subscribe by $port"
     done
 }
 
@@ -103,10 +103,10 @@ while getopts "t:m:h:H:U:D:" opt; do
 done
 
 trap 'cleanup' EXIT
-exec 3>>~/allthingshonk/honk.log
+exec 3>~/allthingshonk/honk.log
 # shellcheck source=honk-manage.conf
 . ~/allthingshonk/honk-manage.conf
-
+set -x
 down_servers=()
 up_servers=()
 get_servers 1>&3 2>&1
