separate subscribe-all as a separate command

diff --git a/honk-manage b/honk-manage
--- a/honk-manage
+++ b/honk-manage
@@ -23,9 +23,6 @@ init(){
     printf "%s\n" "$uname" "$pw" "$listen" "$domain" |
 	honk init || exit 1
     up
-    cd "$datadir/" || exit 1
-    honk-aggressively "$port" subscribe-all
-    [[ $task = "up" ]] && exit
 }
 
 up(){
@@ -50,6 +47,10 @@ timed_sleep(){
 random_sleep(){
    rand=$((1 + RANDOM % (60*60)))
    timed_sleep "$rand"
+}
+
+subscribe_all(){
+    die "not implemented"
 }
 
 set -x
@@ -83,6 +84,9 @@ shift
 
 if [[ $task != "init" ]] && ! [[ -d "$datadir" ]]; then
     die "$datadir hasn't been inited"
+elif [[ $task = "init" ]]; then
+    init
+    exit
 fi
 
 cd "$datadir" || exit 1
@@ -108,9 +112,13 @@ case $task in
     purge)
 	down
 	cd "$HOME" || exit 1
-	rm "$datadir"
+	rm -r "$datadir"
+	;;
+    subscribe-all)
+	subscribe-all
+	exit 1
 	;;
     *)
-        echo "Invalid option.Try up, down or forceDown"
+        die "Invalid option.Try up, down or forceDown"
         ;;
 esac
diff --git a/honk-manager b/honk-manager
--- a/honk-manager
+++ b/honk-manager
@@ -58,9 +58,16 @@ up_servers_func(){
     done
 }
 
+subscribe_all(){
+    for (( i=0; i<"$totalservers"; i++)); do
+	port=$((5000+i))
+	honk-manage "$port" subscribe-all || die "couldn't subscribe by $port"
+    done
+}
+
 cleanup(){
     set -x
-    echo exit > "$rundir/peep" 
+    [[ $start ]] && echo exit > "$rundir/peep" 
     declare -p up_servers
     pkill --exact honk
     pkill --exact honk-servers
@@ -103,9 +110,13 @@ exec 3>>~/allthingshonk/honk.log
 down_servers=()
 up_servers=()
 get_servers 1>&3 2>&1
+sleep 1
+subscribe_all
 
 mkfifo "$rundir/peep"
 peeping-tom "$totalservers" "$updistribution" "$downdistribution" "$honkdistribution" &
+
+start=true
 honk-servers "$totalservers" "$honkdistribution" "$honktime" &
 
 for ((i=0; i<maxruns; i++)) ; do
