retry on error for curl (bad cookies/stale/.../)

diff --git a/honk-aggressively b/honk-aggressively
--- a/honk-aggressively
+++ b/honk-aggressively
@@ -2,17 +2,28 @@
 usage(){
     cat >&2
     exit 1
-}<<EOF
+}<<\EOF
 honk-aggressively _port_ [attached-file]
 the text is read from stdin.
 hostname is https://bikalpa$port.ashwink.com.np
 EOF
 
+die(){
+    printf "%s\n" "$@" >&2
+    exit 1
+}
+login(){
+    "${curl[@]}" -d "username=$uname" -d "password=$pw" "$domain/dologin" > "$tmpfile" || die "couldn't login"
+}
+get_csrf(){
+    "${curl[@]}" "$domain/" > "$tmpfile" || die "couldn't connect"
+    csrf=$(awk  -F'"' 'BEGIN{ e = 1 } /csrftoken =/{ print $2; e = 0} END { exit e }' "$tmpfile")
+}
+
 if (( $# < 1 )); then
     usage
 fi
 
-file=""
 case $# in
     2)
 	file=$2
@@ -28,17 +39,32 @@ shift
 pw=$uname
 domain="https://$uname.ashwink.com.np"
 cookie="honk-$uname.txt"
-curl=(curl -f -b "$cookie" -c "$cookie")
+tmpfile="/tmp/honking.$$.html"
+trap 'rm "$tmpfile"' EXIT
+curl=(curl -sf -b "$cookie" -c "$cookie")
 
 if ! [[ -f "$cookie" ]]; then
-    "${curl[@]}" -d "username=$uname" -d "password=$pw" "$domain/dologin"
+    login
 fi
 
-csrf=$("${curl[@]}" "$domain/" | awk -F\" '/csrftoken =/{ print $2; }')
+if ! get_csrf; then
+    echo "trying to login" >&2
+    login
+    get_csrf
+fi
 
 if [[ $file ]]; then
     curl=("${curl[@]}" -F "donk=@$file")
 fi
 
 printf '%s\n' 'honk:' >&2
-"${curl[@]}" -F "CSRF=$csrf" -F "noise=<-" "$domain/honk"
+"${curl[@]}" -iF "CSRF=$csrf" -F "noise=<-" "$domain/honk" > "$tmpfile"
+status=$?
+
+if head -n1 "$tmpfile" | grep -qF 'HTTP/1.1 303 See Other'; then
+    awk -v"host=$domain" '/Location:/{printf "%s%s\n", host, $2}' "$tmpfile"
+else
+    status=1
+fi
+
+exit "$status"
