subscribe on both ends

diff --git a/honk-aggressively b/honk-aggressively
--- a/honk-aggressively
+++ b/honk-aggressively
@@ -33,14 +33,23 @@ lorem(){
     LC_ALL=C grep -"m$chars" -aEo '[[:alnum:]]' /dev/urandom | tr -d '\n' | paste -s
 }
 
-subscribe() {
+subscribe-all() {
     get_csrf "/honkers"
-    for i; do
-	[[ i == $port ]] && continue
-	honker=bikalpa$i
-	url="https://$honker.ashwink.com.np/u/$honker"
-	"${curl[@]}" -iF "url=$url" "$domain/submithonker"
+    cd "$datadir/../" || die "couldn't cd"
+    for i in */; do
+	i=${i%/}
+	[[ "$i" = "$port" ]] && continue
+	set -x
+	subscribe "$i"
+	honk-aggressively "$i" subscribe "$port" &
+	set +x
     done
+}
+
+subscribe(){
+    honker=$machine$1
+    url="https://$1.$machine.ashwink.com.np/u/$honker"
+    "${curl[@]}" -iF "url=$url" "$domain/submithonker"
 }
 
 bark(){
@@ -63,21 +72,29 @@ fi
 
 port=$1
 shift
+# shellcheck source=honk-manage.conf
 . ~/allthingshonk/honk-manage.conf
-uname=bikalpa$port
+uname=$machine$port
 pw=$uname
-domain="https://$uname.ashwink.com.np"
+domain="https://$port.$machine.ashwink.com.np"
 cookie="$rundir/honk-$uname.txt"
 
 tmpfile="/tmp/honking.$$.html"
 trap 'rm "$tmpfile"' EXIT
 curl=(curl -f -b "$cookie" -c "$cookie")
 
-case $1 in
+action=$1
+shift
+case $action in
     bark|'')
 	bark
 	;;
     subscribe)
+	get_csrf "/honkers"
+	(( $# < 1 )) && usage
 	subscribe "$@"
+	;;
+    subscribe-all)
+	subscribe-all
 	;;
 esac
